### ISSUE TITLE
Babel 2.12.0 onwards require Python 3.7

### ISSUE THREAD

**Issue by jamesmyatt** [conda-forge/babel-feedstock#25]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

See https://babel.pocoo.org/en/latest/changelog.html. v2.12.0 removes Python 3.6 support.

Recipe needs to be updated and previous 2.12.x releases should be marked as broken (https://conda-forge.org/docs/maintainer/updating_pkgs.html#removing-broken-packages).

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by jamesmyatt** [comment]
@frol. Have you marked the old builds as broken?

**Comment by frol** [comment]
@jamesmyatt Nope, I don't have the capacity to deal with it. Can you do that, please?

**Comment by jamesmyatt** [comment]
I can try

**Comment by jamesmyatt** [comment]
The 2.12.0 and 2.12.1 metadata should have been patched now.
